spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ms
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=wikimedia;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123@ace
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
        show-sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update
